apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbit-jetstream.fullname" . }}-nats-headless
  labels:
    {{- include "rabbit-jetstream.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "rabbit-jetstream.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: nats
  ports:
    - {name: client, port: 4222, targetPort: client}
    - {name: cluster, port: 6222, targetPort: cluster}
    - {name: monitor, port: 8222, targetPort: monitor}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbit-jetstream.fullname" . }}-nats
  labels:
    {{- include "rabbit-jetstream.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  selector:
    app.kubernetes.io/name: {{ include "rabbit-jetstream.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: nats
  ports:
    - {name: client, port: 4222, targetPort: client}
