{{- if not .Values.auth.existingSecret }}
{{- $name := include "rabbit-jetstream.authSecret" . }}
{{- $current := lookup "v1" "Secret" .Release.Namespace $name }}
{{- $password := randAlphaNum 32 }}
{{- $adminToken := randAlphaNum 48 }}
{{- if and $current $current.data }}
{{- $password = (index $current.data "nats-password" | b64dec) }}
{{- $adminToken = (index $current.data "admin-token" | b64dec) }}
{{- end }}
{{- $passwordHash := htpasswd .Values.auth.username $password | trimPrefix (printf "%s:" .Values.auth.username) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    {{- include "rabbit-jetstream.labels" . | nindent 4 }}
type: Opaque
data:
  nats-username: {{ .Values.auth.username | b64enc | quote }}
  nats-password: {{ $password | b64enc | quote }}
  nats-password-bcrypt: {{ $passwordHash | b64enc | quote }}
  admin-token: {{ $adminToken | b64enc | quote }}
{{- end }}
