import React,{useEffect,useState} from "react";
const blank={username:"",password:"",memberships:[],disabled:false,platform_admin:false};
const defaults=tenants=>tenants.length?[{tenant:tenants[0],role:"operator"}]:[];
export function AccessManagement({api,language,actor}){
 const t=(en,zh)=>language==="zh"?zh:en;
 const [accounts,setAccounts]=useState([]),[tenants,setTenants]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
 const load=async()=>{setError("");try{const [a,ts]=await Promise.all([api.request("/api/v1/access/accounts"),api.request("/api/v1/access/tenants")]);setAccounts(a.body.items);setTenants(ts.body.items);setForm(v=>v.memberships.length?v:{...v,memberships:defaults(ts.body.items)});}catch{setError(t("Access management data could not be loaded.","无法加载访问管理数据。"));}};
 useEffect(()=>{void load();},[]);
 const reset=()=>{setEditing("");setForm({...blank,memberships:defaults(tenants)});},choose=a=>{setEditing(a.username);setForm({...a,password:""});setNotice("");setError("");};
 const member=id=>form.memberships.find(v=>v.tenant===id),toggle=id=>setForm(v=>({...v,memberships:v.memberships.some(m=>m.tenant===id)?v.memberships.filter(m=>m.tenant!==id):[...v.memberships,{tenant:id,role:"auditor"}]})),role=(id,value)=>setForm(v=>({...v,memberships:v.memberships.map(m=>m.tenant===id?{...m,role:value}:m)}));
 const save=async e=>{e.preventDefault();setBusy(true);setNotice("");setError("");try{await api.request(editing?`/api/v1/access/accounts/${encodeURIComponent(editing)}`:"/api/v1/access/accounts",{method:editing?"PUT":"POST",body:form});await load();reset();setNotice(t("Account saved. Permission changes invalidate earlier tokens.","账户已保存；权限变化会使旧令牌失效。"));}catch(x){setError(x?.body?.error?.message??t("Account could not be saved.","账户无法保存。"));}finally{setBusy(false);}};
 const remove=async a=>{if(!window.confirm(t(`Delete ${a.username}?`,`删除 ${a.username}？`)))return;setBusy(true);try{await api.request(`/api/v1/access/accounts/${encodeURIComponent(a.username)}`,{method:"DELETE"});await load();if(editing===a.username)reset();setNotice(t("Account deleted.","账户已删除。"));}catch(x){setError(x?.body?.error?.message??t("Account could not be deleted.","账户无法删除。"));}finally{setBusy(false);}};
 return <section className="access-management" aria-labelledby="access-heading"><h2 id="access-heading">{t("Tenant access management","租户访问管理")}</h2><p>{t("Each membership has its own role. Tenant backends and NATS credentials remain protected server configuration.","每个租户成员关系拥有独立角色。租户后端和 NATS 凭据仍由受保护的服务端配置管理。")}</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="table-scroll"><table><thead><tr><th>{t("User","用户")}</th><th>{t("Tenant roles","租户角色")}</th><th>{t("Status","状态")}</th><th>{t("Admin","管理员")}</th><th>{t("Actions","操作")}</th></tr></thead><tbody>{accounts.map(a=><tr key={a.username}><td><code>{a.username}</code>{actor===`local:${a.username}`?t(" (current)","（当前）"):""}</td><td>{a.memberships.map(m=>`${m.tenant}: ${m.role}`).join(", ")}</td><td>{a.disabled?t("Disabled","已禁用"):t("Enabled","已启用")}</td><td>{a.platform_admin?t("Yes","是"):t("No","否")}</td><td><button type="button" disabled={busy} onClick={()=>choose(a)}>{t("Edit","编辑")}</button> <button type="button" disabled={busy} onClick={()=>void remove(a)}>{t("Delete","删除")}</button></td></tr>)}</tbody></table></div>
 <form className="access-account-form" onSubmit={save}><h3>{editing?t("Edit account","编辑账户"):t("Create account","创建账户")}</h3><label>{t("Username","用户名")}<input required pattern="[A-Za-z0-9._-]{1,128}" disabled={busy||Boolean(editing)} value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>{editing?t("New password (optional)","新密码（可选）"):t("Password (12+ characters)","密码（至少 12 个字符）")}<input type="password" autoComplete="new-password" required={!editing} minLength={editing?0:12} disabled={busy} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><fieldset><legend>{t("Tenant memberships and roles","租户成员关系与角色")}</legend>{tenants.map(id=>{const m=member(id);return <div className="membership-row" key={id}><label><input type="checkbox" checked={Boolean(m)} disabled={busy} onChange={()=>toggle(id)}/><code>{id}</code></label><select aria-label={t(`Role in ${id}`,`${id} 中的角色`)} value={m?.role??"auditor"} disabled={busy||!m} onChange={e=>role(id,e.target.value)}><option>operator</option><option>auditor</option></select></div>;})}</fieldset><label className="access-check"><input type="checkbox" checked={form.platform_admin} disabled={busy} onChange={e=>setForm({...form,platform_admin:e.target.checked})}/>{t("Platform administrator","平台管理员")}</label><label className="access-check"><input type="checkbox" checked={form.disabled} disabled={busy} onChange={e=>setForm({...form,disabled:e.target.checked})}/>{t("Disabled","禁用")}</label><div><button type="submit" disabled={busy||!form.memberships.length}>{t("Save account","保存账户")}</button>{editing&&<button type="button" disabled={busy} onClick={reset}>{t("Cancel","取消")}</button>}</div></form></section>;
}
