import React,{useEffect,useState} from "react";
import {useDialog,DialogHost} from "./dialog.jsx";
import {accessManagementFormatters} from "./access-management-formatters.mjs";
import {accessManagementLabels} from "./access-management-labels.mjs";
const blank={username:"",password:"",memberships:[],disabled:false,platform_admin:false};
const defaults=tenants=>tenants.length?[{tenant:tenants[0],role:"operator"}]:[];
export function AccessManagement({api,language,actor}){
 const format=accessManagementFormatters(language);
 const text=accessManagementLabels(language);
 const dialog=useDialog();
 const [accounts,setAccounts]=useState([]),[tenants,setTenants]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
 const load=async()=>{setError("");try{const [a,ts]=await Promise.all([api.request("/api/v1/access/accounts"),api.request("/api/v1/access/tenants")]);setAccounts(a.body.items);setTenants(ts.body.items);setForm(v=>v.memberships.length?v:{...v,memberships:defaults(ts.body.items)});}catch{setError(text.access_management_data_could_not_be_loaded);}};
 useEffect(()=>{void load();},[]);
 const reset=()=>{setEditing("");setForm({...blank,memberships:defaults(tenants)});},choose=a=>{setEditing(a.username);setForm({...a,password:""});setNotice("");setError("");};
 const member=id=>form.memberships.find(v=>v.tenant===id),toggle=id=>setForm(v=>({...v,memberships:v.memberships.some(m=>m.tenant===id)?v.memberships.filter(m=>m.tenant!==id):[...v.memberships,{tenant:id,role:"auditor"}]})),role=(id,value)=>setForm(v=>({...v,memberships:v.memberships.map(m=>m.tenant===id?{...m,role:value}:m)}));
 const save=async e=>{e.preventDefault();setBusy(true);setNotice("");setError("");try{await api.request(editing?`/api/v1/access/accounts/${encodeURIComponent(editing)}`:"/api/v1/access/accounts",{method:editing?"PUT":"POST",body:form});await load();reset();setNotice(text.account_saved_permission_changes_invalidate_earlier_tokens);}catch(x){setError(x?.body?.error?.message??text.account_could_not_be_saved);}finally{setBusy(false);}};
 const remove=async a=>{if(!await dialog.confirm(format.deleteAccount(a.username),{tone:"danger",confirmLabel:text.delete}))return;setBusy(true);try{await api.request(`/api/v1/access/accounts/${encodeURIComponent(a.username)}`,{method:"DELETE"});await load();if(editing===a.username)reset();setNotice(text.account_deleted);}catch(x){setError(x?.body?.error?.message??text.account_could_not_be_deleted);}finally{setBusy(false);}};
 return <section className="access-management" aria-labelledby="access-heading"><h2 id="access-heading">{text.tenant_access_management}</h2><p>{text.each_membership_has_its_own_role_tenant}</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="table-scroll"><table><caption className="visually-hidden">{text.tenant_accounts}</caption><thead><tr><th>{text.user}</th><th>{text.tenant_roles}</th><th>{text.status}</th><th>{text.admin}</th><th>{text.actions}</th></tr></thead><tbody>{accounts.map(a=><tr key={a.username}><td><code>{a.username}</code>{actor===`local:${a.username}`?text.current:""}</td><td>{a.memberships.map(m=>`${m.tenant}: ${m.role}`).join(", ")}</td><td>{a.disabled?text.disabled:text.enabled}</td><td>{a.platform_admin?text.yes:text.no}</td><td><button type="button" disabled={busy} onClick={()=>choose(a)}>{text.edit}</button> <button type="button" disabled={busy} onClick={()=>void remove(a)}>{text.delete}</button></td></tr>)}</tbody></table></div>
 <form className="access-account-form" onSubmit={save}><h3>{editing?text.edit_account:text.create_account}</h3><label>{text.username}<input required pattern="[A-Za-z0-9._-]{1,128}" disabled={busy||Boolean(editing)} value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>{editing?text.new_password_optional:text.password_12_characters}<input type="password" autoComplete="new-password" required={!editing} minLength={editing?0:12} disabled={busy} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><fieldset><legend>{text.tenant_memberships_and_roles}</legend>{tenants.map(id=>{const m=member(id);return <div className="membership-row" key={id}><label><input type="checkbox" checked={Boolean(m)} disabled={busy} onChange={()=>toggle(id)}/><code>{id}</code></label><select aria-label={format.roleIn(id)} value={m?.role??"auditor"} disabled={busy||!m} onChange={e=>role(id,e.target.value)}><option>operator</option><option>auditor</option></select></div>;})}</fieldset><label className="access-check"><input type="checkbox" checked={form.platform_admin} disabled={busy} onChange={e=>setForm({...form,platform_admin:e.target.checked})}/>{text.platform_administrator}</label><label className="access-check"><input type="checkbox" checked={form.disabled} disabled={busy} onChange={e=>setForm({...form,disabled:e.target.checked})}/>{text.disabled}</label><div><button type="submit" disabled={busy||!form.memberships.length}>{text.save_account}</button>{editing&&<button type="button" disabled={busy} onClick={reset}>{text.cancel}</button>}</div></form><DialogHost dialog={dialog.dialog} language={language}/></section>;
}
