const catalogs = Object.freeze({
  en: Object.freeze({
    "operational_alerts": "Operational alerts",
    "source_server_configured_prometheus_rules_this_console": "Source: server-configured Prometheus rules. This console reads state only; it does not send notifications. Inactive means not currently firing, not proven recovery. Recovered is shown only after this management process observed a firing-to-inactive transition.",
    "refresh_alerts": "Refresh alerts",
    "reading_alert_rules": "Reading alert rules…",
    "prometheus_alert_backend_is_not_configured": "Prometheus alert backend is not configured.",
    "alert_read_was_denied": "Alert read was denied.",
    "alert_rules_are_unavailable_or_incompatible": "Alert rules are unavailable or incompatible.",
    "open_prometheus_alerts": "Open Prometheus alerts",
    "no_browser_visible_external_alert_console_is": "No browser-visible external alert console is configured.",
    "incomplete_alert_coverage_missing_repository_rules": "Incomplete alert coverage. Missing repository rules: ",
    "observed_at": "Observed at",
    "no_repository_defined_rules_were_returned_alert": "No repository-defined rules were returned; alert coverage is unknown.",
    "configured_operational_rules": "Configured operational rules",
    "rule": "Rule",
    "severity": "Severity",
    "state": "State",
    "threshold_expression": "Threshold expression",
    "for_seconds": "For (seconds)",
    "active_since": " Active since ",
    "recovered_at": " Recovered at ",
  }),
  zh: Object.freeze({
    "operational_alerts": "运维告警",
    "source_server_configured_prometheus_rules_this_console": "来源：服务端配置的 Prometheus 规则。本控制台只读取状态，不发送通知。未触发只表示当前未触发，不证明已恢复；只有本管理进程观察到触发转为未触发后才显示已恢复。",
    "refresh_alerts": "刷新告警",
    "reading_alert_rules": "正在读取告警规则…",
    "prometheus_alert_backend_is_not_configured": "未配置 Prometheus 告警后端。",
    "alert_read_was_denied": "告警读取被拒绝。",
    "alert_rules_are_unavailable_or_incompatible": "告警规则不可用或响应不兼容。",
    "open_prometheus_alerts": "打开 Prometheus 告警",
    "no_browser_visible_external_alert_console_is": "未配置浏览器可访问的外部告警控制台。",
    "incomplete_alert_coverage_missing_repository_rules": "告警覆盖不完整。缺少仓库规则：",
    "observed_at": "观测时间",
    "no_repository_defined_rules_were_returned_alert": "未返回仓库定义的规则，告警覆盖情况未知。",
    "configured_operational_rules": "已配置运维规则",
    "rule": "规则",
    "severity": "级别",
    "state": "状态",
    "threshold_expression": "阈值表达式",
    "for_seconds": "持续时间（秒）",
    "active_since": " 触发时间 ",
    "recovered_at": " 恢复时间 ",
  }),
});

export function alertsLabels(language) {
  return catalogs[language] ?? catalogs.en;
}
