import {latestRead} from "./api.mjs";
import {validObservationTime} from "./observation-time.mjs";
const names=new Set(["RabbitJetStreamJetStreamUnavailable","RabbitJetStreamControllerStalled","RabbitJetStreamNATSNodeUnavailable","RabbitJetStreamDeadLetterFailures","RabbitJetStreamQueueBacklogHigh","RabbitJetStreamManagementHighErrorRate"]),states=new Set(["inactive","pending","firing","recovered"]),severities=new Set(["warning","critical"]);
const clean=(value,max)=>typeof value==="string"&&value.length<=max&&!/[\u0000-\u001f\u007f]/.test(value);
export function decodeAlerts(value){
  if(value?.schema!=="rjs.operational-alerts.v1"||value.source!=="prometheus"||!validObservationTime(value.observedAt)||!Array.isArray(value.rules)||value.rules.length>6||!Array.isArray(value.missingRules)||value.missingRules.length>6)throw Error("invalid alerts");
  const seen=new Set(),rules=value.rules.map(rule=>{if(!names.has(rule?.name)||seen.has(rule.name)||!states.has(rule.state)||!severities.has(rule.severity)||!clean(rule.query,2048)||!/^\d+(?:\.\d+)?$/.test(rule.duration)||!clean(rule.summary,512)||!clean(rule.description,2048)||rule.activeAt!==undefined&&!validObservationTime(rule.activeAt)||rule.recoveredAt!==undefined&&!validObservationTime(rule.recoveredAt)||rule.state==="recovered"&&!rule.recoveredAt||rule.state!=="recovered"&&rule.recoveredAt!==undefined)throw Error("invalid alert rule");seen.add(rule.name);return{name:rule.name,query:rule.query,duration:rule.duration,severity:rule.severity,summary:rule.summary,description:rule.description,state:rule.state,...(rule.activeAt?{activeAt:rule.activeAt}:{}),...(rule.recoveredAt?{recoveredAt:rule.recoveredAt}:{})};});
  const missingRules=value.missingRules.map(name=>{if(!names.has(name)||seen.has(name))throw Error("invalid missing alert rule");seen.add(name);return name;});if(seen.size!==names.size)throw Error("incomplete alert coverage accounting");
  let consoleUrl;if(value.consoleUrl!==undefined){const parsed=new URL(value.consoleUrl);if(parsed.username||parsed.password||parsed.search||parsed.hash||parsed.pathname!=="/alerts"||parsed.protocol!=="https:"&&!(parsed.protocol==="http:"&&["127.0.0.1","[::1]"].includes(parsed.hostname)))throw Error("invalid alert console URL");consoleUrl=parsed.href;}
  return{schema:value.schema,source:value.source,observedAt:value.observedAt,rules,missingRules,...(consoleUrl?{consoleUrl}:{})};
}
export function createAlerts(api){const reader=latestRead(api),listeners=new Set();let state={phase:"idle"};const emit=next=>{state=next;for(const listener of listeners)listener();};return{snapshot:()=>state,subscribe(listener){listeners.add(listener);return()=>listeners.delete(listener);},async load(){reader.cancel();emit({phase:"loading"});try{const response=await reader.run("/api/v1/alerts");if(response.stale)return;emit({phase:"ready",value:decodeAlerts(response.result.body)});}catch(error){emit({phase:"error",failure:error.code==="alerts_api_disabled"?"disabled":error.status===401||error.status===403?"denied":"unavailable"});}},clear(){reader.cancel();emit({phase:"idle"});}};}
