const key="rjs.oidc.pkce.v1",validURL=(raw,{callback=false}={})=>{const value=new URL(raw);if(value.username||value.password||value.hash||value.protocol!=="https:"&&!(value.protocol==="http:"&&["127.0.0.1","[::1]"].includes(value.hostname))||callback&&value.pathname!=="/admin/oidc/callback")throw Error("invalid OIDC URL");return value;};
const encode=bytes=>btoa(String.fromCharCode(...bytes)).replaceAll("+","-").replaceAll("/","_").replace(/=+$/,""),random=crypto=>encode(crypto.getRandomValues(new Uint8Array(32)));
export function decodeBrowserOIDC(body,origin){if(body?.schema!=="rjs.browser-oidc.v1"||typeof body.clientId!=="string"||!body.clientId||!Array.isArray(body.scopes)||body.scopes.join(" ")!=="openid profile")throw Error("invalid OIDC config");const authorizationEndpoint=validURL(body.authorizationEndpoint).href,callbackUrl=validURL(body.callbackUrl,{callback:true});if(callbackUrl.origin!==origin)throw Error("foreign OIDC callback");let logoutEndpoint;if(body.logoutEndpoint!==undefined){logoutEndpoint=validURL(body.logoutEndpoint).href;}return{authorizationEndpoint,clientId:body.clientId,callbackUrl:callbackUrl.href,scopes:[...body.scopes],...(logoutEndpoint?{logoutEndpoint}:{})};}
export function createBrowserOIDC(api,session,{browser=window,storage=()=>browser.sessionStorage,crypto=browser.crypto,now=Date.now}={}){
  let config=null;
  async function load(){try{const {body}=await api.request("/api/v1/oidc/config");config=decodeBrowserOIDC(body,browser.location.origin);return config;}catch(error){config=null;if(error.status===404)return null;throw error;}}
  async function start(){const current=config??await load();if(!current)throw Error("browser OIDC disabled");if(typeof crypto?.subtle?.digest!=="function")throw Error("PKCE unavailable");const state=random(crypto),verifier=random(crypto)+random(crypto),challenge=encode(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(verifier)))),returnPath=browser.location.pathname.startsWith("/admin/")&&!browser.location.search&&!browser.location.hash?browser.location.pathname:"/admin/overview";storage().setItem(key,JSON.stringify({state,verifier,createdAt:now(),callbackUrl:current.callbackUrl,clientId:current.clientId,returnPath}));const target=new URL(current.authorizationEndpoint);target.searchParams.set("response_type","code");target.searchParams.set("client_id",current.clientId);target.searchParams.set("redirect_uri",current.callbackUrl);target.searchParams.set("scope",current.scopes.join(" "));target.searchParams.set("state",state);target.searchParams.set("code_challenge",challenge);target.searchParams.set("code_challenge_method","S256");browser.location.assign(target.href);}
  async function complete(){if(browser.location.pathname!=="/admin/oidc/callback")return false;const params=new URLSearchParams(browser.location.search),raw=storage().getItem(key);storage().removeItem(key);let pending;try{pending=JSON.parse(raw??"");}catch{pending=null;}const returnPath=typeof pending?.returnPath==="string"&&pending.returnPath.startsWith("/admin/")&&pending.returnPath!=="/admin/oidc/callback"?pending.returnPath:"/admin/overview";browser.history.replaceState(null,"",returnPath);browser.dispatchEvent(new browser.Event("popstate"));for(const [name] of params)if(!["code","state","session_state","iss","error","error_description"].includes(name)||params.getAll(name).length!==1)throw Error("invalid OIDC callback");if(params.has("error")||!pending||typeof pending.state!=="string"||params.get("state")!==pending.state||typeof params.get("code")!=="string"||!params.get("code")||typeof pending.verifier!=="string"||now()-pending.createdAt<0||now()-pending.createdAt>600000)throw Error("invalid OIDC callback");const current=await load();if(!current||current.callbackUrl!==pending.callbackUrl||current.clientId!==pending.clientId)throw Error("OIDC configuration changed");const {body}=await api.request("/api/v1/oidc/token",{method:"POST",body:{schema:"rjs.browser-oidc-callback.v1",code:params.get("code"),verifier:pending.verifier}});if(body?.schema!=="rjs.browser-oidc-token.v1"||typeof body.token!=="string"||!body.token)throw Error("invalid OIDC token response");await session.signIn(body.token);return true;}
  function logout(){session.clear();if(config?.logoutEndpoint)browser.location.assign(config.logoutEndpoint);}
  return{load,start,complete,logout,get config(){return config;}};
}
