const catalogs = Object.freeze({
  en: Object.freeze({
    "reading_compatibility_metadata": "Reading compatibility metadata…",
    "source_unavailable_denied_or_incompatible_previous_metadata": "Source unavailable, denied or incompatible; previous metadata cleared.",
    "read_completed": "Read completed",
    "unreported": "Unreported",
    "compatibility": "Compatibility",
    "independent_reported_metadata_not_an_atomic_snapshot": "Independent reported metadata, not an atomic snapshot, artifact attestation or production qualification. No upgrade, restart or feature changes are performed here.",
    "refresh_compatibility_metadata": "Refresh compatibility metadata",
    "management_process_build": "Management process build",
    "reported_version": "Reported version",
    "go_runtime": "Go runtime",
    "build_target": "Build target",
    "vcs_revision": "VCS revision",
    "revision_source": "Revision source",
    "modified_source_at_build": "Modified source at build",
    "embedded_ui_identity": "Embedded UI identity",
    "embedded_ui_files": "Embedded UI files",
    "the_ui_digest_identifies_the_exact_embedded": "The UI digest identifies the exact embedded files served by this process; it is not a signature or qualification verdict. Missing VCS metadata does not prove a clean or released build.",
    "published_native_sdk_contract": "Published native SDK contract",
    "schema": "Schema",
    "declared_availability": "Declared availability",
    "delivery_guarantee": "Delivery guarantee",
    "publisher_confirmation": "Publisher confirmation",
    "acknowledgment_policy": "Acknowledgment policy",
    "message_headers": "Message headers",
    "required": "required",
    "optional": "optional",
    "a_published_contract_does_not_prove_an": "A published contract does not prove an SDK release is available or compatible with an installed client. This is not RabbitMQ wire-protocol compatibility.",
  }),
  zh: Object.freeze({
    "reading_compatibility_metadata": "正在读取兼容性元数据…",
    "source_unavailable_denied_or_incompatible_previous_metadata": "来源不可用、拒绝访问或不兼容，已清除此前元数据。",
    "read_completed": "读取完成",
    "unreported": "未报告",
    "compatibility": "兼容性",
    "independent_reported_metadata_not_an_atomic_snapshot": "各来源独立报告的元数据，不是原子快照、制品认证或生产资格。此处不执行升级、重启或功能变更。",
    "refresh_compatibility_metadata": "刷新兼容性元数据",
    "management_process_build": "管理进程构建",
    "reported_version": "报告版本",
    "go_runtime": "Go 运行时",
    "build_target": "构建目标",
    "vcs_revision": "VCS 版本",
    "revision_source": "版本来源",
    "modified_source_at_build": "构建时源码已修改",
    "embedded_ui_identity": "内嵌 UI 身份",
    "embedded_ui_files": "内嵌 UI 文件数",
    "the_ui_digest_identifies_the_exact_embedded": "UI 摘要标识该进程实际提供的精确内嵌文件集；它不是签名或资格结论。缺少 VCS 元数据不能证明构建干净或已经发布。",
    "published_native_sdk_contract": "发布的原生 SDK 契约",
    "schema": "Schema",
    "declared_availability": "声明的可用阶段",
    "delivery_guarantee": "投递保证",
    "publisher_confirmation": "发布确认",
    "acknowledgment_policy": "确认策略",
    "message_headers": "消息头",
    "required": "必填",
    "optional": "可选",
    "a_published_contract_does_not_prove_an": "公开契约不证明 SDK 已发布或与已安装客户端兼容，也不代表 RabbitMQ 线协议兼容。",
  }),
});

export function compatibilityLabels(language) {
  return catalogs[language] ?? catalogs.en;
}
