import React,{useEffect,useMemo,useState,useSyncExternalStore} from "react";
import {createConnections,connectionCounters} from "./connections.mjs";
import {nodeConnectionsURL,nodeDetailURL,nodeConnectionURL} from "./routes.mjs";
import {connectionLabels} from "./connection-labels.mjs";
export function Connections({api,route,router,language,refreshSeconds=10}){
  const zh=language==="zh",t=(en,cn)=>zh?cn:en,{id,query}=route,accessible=connectionLabels(language);
  const view=useMemo(()=>createConnections(api,id,query),[api,id,query.offset,query.limit,query.cid]);
  const state=useSyncExternalStore(view.subscribe,view.snapshot),{page}=state;
  const [hidden,setHidden]=useState(document.hidden),[,tick]=useState(0),[cid,setCID]=useState(query.cid??""),[cidError,setCIDError]=useState(false),[identityKind,setIdentityKind]=useState("user"),[identityValue,setIdentityValue]=useState(""),[identityError,setIdentityError]=useState(false),now=Date.now();
  useEffect(()=>{setCID(query.cid??"");setCIDError(false);},[query.cid]);
  useEffect(()=>{view.refresh.setInterval(refreshSeconds*1000);},[view,refreshSeconds]);
  useEffect(()=>{const changed=()=>{setHidden(document.hidden);view.refresh.visibility(document.hidden);};setHidden(document.hidden);document.addEventListener("visibilitychange",changed);view.refresh.start(document.hidden);const timer=setInterval(()=>tick(Date.now()),1000);return()=>{clearInterval(timer);document.removeEventListener("visibilitychange",changed);view.clear();};},[view]);
  const navigate=(event,url)=>{if(event.button===0&&!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&!event.altKey){event.preventDefault();router.navigate(url);}};
  const change=changes=>{const next={...query,...changes};if(next.cid===undefined)delete next.cid;router.navigate(nodeConnectionsURL(id,next));};
  const searchCID=event=>{event.preventDefault();const value=cid.trim();let valid=value===""||/^[0-9]+$/.test(value);if(valid&&value!==""){const parsed=BigInt(value);valid=parsed>=1n&&parsed<=18446744073709551615n;}if(!valid){setCIDError(true);return;}setCIDError(false);change({offset:0,cid:value||undefined});};
  const searchIdentity=event=>{event.preventDefault();const value=identityValue;if(!value||value.length>256||/[\u0000-\u001f\u007f]/.test(value)){setIdentityError(true);return;}setIdentityError(false);void view.search(identityKind,value,0,query.limit);};
  const errors={missing:t("Node not found in complete configured-endpoint coverage.","完整配置端点覆盖中未找到节点。"),ambiguous:t("Multiple endpoints report this node ID; no connection page shown.","多个端点报告此节点 ID，不展示连接页。"),denied:t("Connection read denied.","连接读取被拒绝。"),disabled:t("Resource reads disabled.","资源读取已禁用。"),query:t("Connection query rejected.","连接查询被拒绝。"),limit:t("Connection search exceeds the 1,000-connection safety boundary.","连接搜索超过 1,000 个连接的安全边界。"),invalid:t("Invalid connection response; old data cleared.","连接响应无效，旧数据已清除。"),unavailable:t("Connection observation unavailable; this is not an empty node.","连接观测不可用，不代表节点没有连接。")};
  return <section className="node-connections" aria-label={accessible.view}><a href={nodeDetailURL(id)} onClick={e=>navigate(e,nodeDetailURL(id))}>{t("Back to node","返回节点")}</a><h2>{t("Node connections","节点连接")}: {id}</h2>
    <p>{t("Open connections on this exact node, sorted by CID. Exact searches run across this node, not on the loaded page. CID alone is not a global identity. Client-name search has a 1,000-open-connection node limit; bounded subscription detail loads explicitly from a connection.","此精确节点的打开连接按 CID 排序。精确搜索在整个节点范围执行，不是在已加载页中筛选。CID 本身不是全局身份；客户端名称搜索要求节点打开连接不超过 1,000 个，有界订阅详情需从连接中显式加载。")}</p>
    <p>{hidden?t("Automatic refresh paused while hidden.","隐藏时暂停自动刷新。"):refreshSeconds===0?t("Automatic refresh disabled; manual only.","自动刷新已关闭，仅手动刷新。"):t(`Refresh ${refreshSeconds}s after completion; failures back off up to 60s.`,`完成后 ${refreshSeconds} 秒刷新，失败退避最长 60 秒。`)}</p>
    <form className="connection-controls" onSubmit={searchCID}><label htmlFor="connection-cid-search">{t("Exact CID","精确 CID")}</label><input id="connection-cid-search" inputMode="numeric" pattern="[0-9]+" maxLength="20" aria-invalid={cidError||undefined} aria-describedby={cidError?"connection-cid-error":undefined} value={cid} onChange={event=>{setCID(event.target.value);setCIDError(false);}}/><button>{t("Search","搜索")}</button><button type="button" disabled={hidden||state.phase==="loading"} onClick={()=>void view.refresh.refresh()}>{t("Refresh connections","刷新连接")}</button>
    <div><label htmlFor="connection-page-size">{t("Connections per page","每页连接数")}</label><select id="connection-page-size" value={query.limit} onChange={e=>change({limit:Number(e.target.value),offset:0})}>{[...new Set([25,50,100,200,query.limit])].sort((a,b)=>a-b).map(n=><option key={n}>{n}</option>)}</select></div></form>
    {cidError&&<p id="connection-cid-error" role="alert">{t("CID must be a decimal integer from 1 through 18446744073709551615.","CID 必须是 1 到 18446744073709551615 的十进制整数。")}</p>}
    <form className="connection-controls" onSubmit={searchIdentity}>
      <label htmlFor="connection-identity-kind">{t("Exact identity field","精确身份字段")}</label><select id="connection-identity-kind" value={identityKind} onChange={e=>setIdentityKind(e.target.value)}><option value="name">{t("Client name","客户端名称")}</option><option value="user">{t("Authorized user","授权用户")}</option><option value="account">{t("Account","账户")}</option><option value="mqtt_client">{t("MQTT client ID","MQTT 客户端 ID")}</option></select>
      <label htmlFor="connection-identity-value">{t("Exact value","精确值")}</label><input id="connection-identity-value" type="password" autoComplete="off" maxLength="256" value={identityValue} aria-invalid={identityError||undefined} aria-describedby={identityError?"connection-identity-error":"connection-identity-note"} onChange={e=>{setIdentityValue(e.target.value);setIdentityError(false);}}/><button>{t("Search identity","搜索身份")}</button>{state.identity&&<button type="button" onClick={()=>void view.clearSearch()}>{t("Clear identity search","清除身份搜索")}</button>}
    </form>
    <p id="connection-identity-note">{t("The exact value stays in this page's memory and is not added to the URL or returned in results. Client-name search is bounded to nodes with at most 1,000 open connections.","精确值仅保留在当前页面内存中，不会写入 URL 或返回结果。客户端名称搜索仅支持打开连接不超过 1,000 个的节点。")}</p>
    {identityError&&<p id="connection-identity-error" role="alert">{t("Enter 1–256 characters without control characters.","请输入 1–256 个不含控制字符的字符。")}</p>}
    {state.phase==="loading"&&<p role="status">{t("Reading connections…","正在读取连接…")}</p>}{state.failure&&<p role="alert">{errors[state.failure]}</p>}
    {page&&<>{(state.phase==="loading"||state.failure)&&<p role="status">{t("Historical page from the last successful read, not current connections.","上次成功读取的历史页，不代表当前连接。")}</p>}
      {(hidden||state.failure||now-Date.parse(state.readAt)>30000||now<Date.parse(state.readAt))&&<p role="status">{t("Stale observation; freshness is not health.","旧观测；新鲜度不代表健康。")}</p>}
      <p>{t("Reported node total","节点报告总数")}: {page.total} · {t("Returned rows","返回行数")}: {page.items.length}</p>
      <p>{t("Server observation","服务端观测")}: <time dateTime={page.observed_at} title={page.observed_at}>{page.observed_at}</time> · {t("Management read","管理读取")}: <time dateTime={page.read_at} title={page.read_at}>{page.read_at}</time></p>
      <p>{t("Pages are live independent reads. Counters are cumulative per connection, except pending bytes and current subscriptions. They are not Consumer pending/ACK backlog or rates.","各页独立实时读取。除待发送字节及当前订阅数外，计数为每连接累计值，不是 Consumer 待投递/待确认积压或速率。")}</p>
      {page.items.length?<div className="table-scroll connection-rows" role="region" tabIndex="0" aria-label={accessible.rows}><table><thead><tr>{["CID",t("Pending bytes","待发送字节"),t("Received messages","接收消息"),t("Sent messages","发送消息"),t("Received bytes","接收字节"),t("Sent bytes","发送字节"),t("Subscriptions","订阅数")].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{page.items.map(row=><tr key={String(row.cid)}><th scope="row"><a href={nodeConnectionURL(id,row.cid,query)} onClick={event=>navigate(event,nodeConnectionURL(id,row.cid,query))}>{String(row.cid)}</a></th>{connectionCounters.map(key=><td key={key}>{row[key]===undefined?t("Unknown","未知"):String(row[key])}</td>)}</tr>)}</tbody></table></div>:<p>{page.total===0?t("No open connections reported.","未报告打开的连接。"):t("This page is empty; return to an earlier page.","本页为空，请返回较早页面。")}</p>}
      {state.identity?<nav className="connection-pagination" aria-label={accessible.pagination}><button disabled={page.offset===0} onClick={()=>void view.searchPage(Math.max(0,page.offset-page.limit))}>{t("Previous","上一页")}</button><span>{page.items.length?`${page.offset+1}–${page.offset+page.items.length}`:"0"} / {page.total}</span><button disabled={page.items.length===0||page.offset+page.limit>=page.total} onClick={()=>void view.searchPage(page.offset+page.limit)}>{t("Next","下一页")}</button></nav>:!query.cid&&<nav className="connection-pagination" aria-label={accessible.pagination}><button disabled={query.offset===0} onClick={()=>change({offset:Math.max(0,Math.min(query.offset-query.limit,Math.floor(Math.max(0,page.total-1)/query.limit)*query.limit))})}>{t("Previous","上一页")}</button><span>{page.items.length?`${query.offset+1}–${query.offset+page.items.length}`:"0"} / {page.total}</span><button disabled={page.items.length===0||query.offset+query.limit>=page.total||query.offset+query.limit>1000000} onClick={()=>change({offset:query.offset+query.limit})}>{t("Next","下一页")}</button></nav>}
    </>}
  </section>;
}
