const catalogs = Object.freeze({
  en: Object.freeze({
    "node_not_found_in_complete_configured_endpoint": "Node not found in complete configured-endpoint coverage.",
    "multiple_endpoints_report_this_node_id_no": "Multiple endpoints report this node ID; no connection page shown.",
    "connection_read_denied": "Connection read denied.",
    "resource_reads_disabled": "Resource reads disabled.",
    "connection_query_rejected": "Connection query rejected.",
    "connection_search_exceeds_the_1_000_connection": "Connection search exceeds the 1,000-connection safety boundary.",
    "invalid_connection_response_old_data_cleared": "Invalid connection response; old data cleared.",
    "connection_observation_unavailable_this_is_not_an": "Connection observation unavailable; this is not an empty node.",
    "back_to_node": "Back to node",
    "node_connections": "Node connections",
    "open_connections_on_this_exact_node_sorted": "Open connections on this exact node, sorted by CID. Exact searches run across this node, not on the loaded page. CID alone is not a global identity. Client-name search has a 1,000-open-connection node limit; bounded subscription detail loads explicitly from a connection.",
    "automatic_refresh_paused_while_hidden": "Automatic refresh paused while hidden.",
    "automatic_refresh_disabled_manual_only": "Automatic refresh disabled; manual only.",
    "exact_cid": "Exact CID",
    "search": "Search",
    "refresh_connections": "Refresh connections",
    "connections_per_page": "Connections per page",
    "cid_must_be_a_decimal_integer_from": "CID must be a decimal integer from 1 through 18446744073709551615.",
    "exact_identity_field": "Exact identity field",
    "client_name": "Client name",
    "authorized_user": "Authorized user",
    "account": "Account",
    "mqtt_client_id": "MQTT client ID",
    "exact_value": "Exact value",
    "search_identity": "Search identity",
    "clear_identity_search": "Clear identity search",
    "the_exact_value_stays_in_this_page": "The exact value stays in this page's memory and is not added to the URL or returned in results. Client-name search is bounded to nodes with at most 1,000 open connections.",
    "enter_1_256_characters_without_control_characters": "Enter 1–256 characters without control characters.",
    "reading_connections": "Reading connections…",
    "historical_page_from_the_last_successful_read": "Historical page from the last successful read, not current connections.",
    "stale_observation_freshness_is_not_health": "Stale observation; freshness is not health.",
    "reported_node_total": "Reported node total",
    "returned_rows": "Returned rows",
    "server_observation": "Server observation",
    "management_read": "Management read",
    "pages_are_live_independent_reads_counters_are": "Pages are live independent reads. Counters are cumulative per connection, except pending bytes and current subscriptions. They are not Consumer pending/ACK backlog or rates.",
    "connection_rows": "Connection rows",
    "pending_bytes": "Pending bytes",
    "received_messages": "Received messages",
    "sent_messages": "Sent messages",
    "received_bytes": "Received bytes",
    "sent_bytes": "Sent bytes",
    "subscriptions": "Subscriptions",
    "unknown": "Unknown",
    "no_open_connections_reported": "No open connections reported.",
    "this_page_is_empty_return_to_an": "This page is empty; return to an earlier page.",
    "previous": "Previous",
    "next": "Next",
  }),
  zh: Object.freeze({
    "node_not_found_in_complete_configured_endpoint": "完整配置端点覆盖中未找到节点。",
    "multiple_endpoints_report_this_node_id_no": "多个端点报告此节点 ID，不展示连接页。",
    "connection_read_denied": "连接读取被拒绝。",
    "resource_reads_disabled": "资源读取已禁用。",
    "connection_query_rejected": "连接查询被拒绝。",
    "connection_search_exceeds_the_1_000_connection": "连接搜索超过 1,000 个连接的安全边界。",
    "invalid_connection_response_old_data_cleared": "连接响应无效，旧数据已清除。",
    "connection_observation_unavailable_this_is_not_an": "连接观测不可用，不代表节点没有连接。",
    "back_to_node": "返回节点",
    "node_connections": "节点连接",
    "open_connections_on_this_exact_node_sorted": "此精确节点的打开连接按 CID 排序。精确搜索在整个节点范围执行，不是在已加载页中筛选。CID 本身不是全局身份；客户端名称搜索要求节点打开连接不超过 1,000 个，有界订阅详情需从连接中显式加载。",
    "automatic_refresh_paused_while_hidden": "隐藏时暂停自动刷新。",
    "automatic_refresh_disabled_manual_only": "自动刷新已关闭，仅手动刷新。",
    "exact_cid": "精确 CID",
    "search": "搜索",
    "refresh_connections": "刷新连接",
    "connections_per_page": "每页连接数",
    "cid_must_be_a_decimal_integer_from": "CID 必须是 1 到 18446744073709551615 的十进制整数。",
    "exact_identity_field": "精确身份字段",
    "client_name": "客户端名称",
    "authorized_user": "授权用户",
    "account": "账户",
    "mqtt_client_id": "MQTT 客户端 ID",
    "exact_value": "精确值",
    "search_identity": "搜索身份",
    "clear_identity_search": "清除身份搜索",
    "the_exact_value_stays_in_this_page": "精确值仅保留在当前页面内存中，不会写入 URL 或返回结果。客户端名称搜索仅支持打开连接不超过 1,000 个的节点。",
    "enter_1_256_characters_without_control_characters": "请输入 1–256 个不含控制字符的字符。",
    "reading_connections": "正在读取连接…",
    "historical_page_from_the_last_successful_read": "上次成功读取的历史页，不代表当前连接。",
    "stale_observation_freshness_is_not_health": "旧观测；新鲜度不代表健康。",
    "reported_node_total": "节点报告总数",
    "returned_rows": "返回行数",
    "server_observation": "服务端观测",
    "management_read": "管理读取",
    "pages_are_live_independent_reads_counters_are": "各页独立实时读取。除待发送字节及当前订阅数外，计数为每连接累计值，不是 Consumer 待投递/待确认积压或速率。",
    "connection_rows": "连接数据行",
    "pending_bytes": "待发送字节",
    "received_messages": "接收消息",
    "sent_messages": "发送消息",
    "received_bytes": "接收字节",
    "sent_bytes": "发送字节",
    "subscriptions": "订阅数",
    "unknown": "未知",
    "no_open_connections_reported": "未报告打开的连接。",
    "this_page_is_empty_return_to_an": "本页为空，请返回较早页面。",
    "previous": "上一页",
    "next": "下一页",
  }),
});

export function connectionsLabels(language) {
  return catalogs[language] ?? catalogs.en;
}
