const catalogs = Object.freeze({
  en: Object.freeze({
    "diagnostics": "Diagnostics",
    "creates_a_temporary_metadata_only_zip_in": "Creates a temporary metadata-only ZIP in this management process. It excludes messages, subscriptions, logs, environment, credentials and full Queue/Stream inventories. It is not a backup or atomic snapshot.",
    "one_collection_runs_at_a_time_at": "One collection runs at a time, at most two jobs are retained, and each expires ten minutes after creation. Restart loses all jobs. Creation is explicit and is never retried automatically.",
    "requesting": "Requesting…",
    "create_metadata_bundle": "Create metadata bundle",
    "the_operation_failed_or_its_response_was": "The operation failed or its response was invalid. Review audit evidence before retrying a create request.",
    "current_diagnostic_job": "Current diagnostic job",
    "current_job": "Current job",
    "state": "State",
    "created": "Created",
    "expires": "Expires",
    "collecting_bounded_metadata": "Collecting bounded metadata…",
    "cancel_collection": "Cancel collection",
    "partial_bundle_one_or_more_sources_were": "Partial bundle: one or more sources were omitted. Inspect the manifest before use.",
    "bundle_manifest": "Bundle manifest",
    "source": "Source",
    "file": "File",
    "bytes": "Bytes",
    "result": "Result",
    "included": "Included",
    "prepare_download": "Prepare download",
    "save_diagnostic_zip": "Save diagnostic ZIP",
    "bytes_2": "bytes",
    "server_completion_does_not_prove_the_browser": "Server completion does not prove the browser saved the file.",
    "no_archive_is_available_for_this_terminal": "No archive is available for this terminal state.",
  }),
  zh: Object.freeze({
    "diagnostics": "诊断包",
    "creates_a_temporary_metadata_only_zip_in": "在当前管理进程内创建临时、仅元数据的 ZIP。不包含消息、订阅、日志、环境变量、凭据及完整 Queue/Stream 清单；它不是备份或原子快照。",
    "one_collection_runs_at_a_time_at": "同一时间只采集一个任务，最多保留两个任务，每项自创建起十分钟过期。进程重启会丢失全部任务；创建必须显式触发且绝不自动重试。",
    "requesting": "正在请求…",
    "create_metadata_bundle": "创建元数据诊断包",
    "the_operation_failed_or_its_response_was": "操作失败或响应无效。重新发起创建请求前请先检查审计证据。",
    "current_diagnostic_job": "当前诊断任务",
    "current_job": "当前任务",
    "state": "状态",
    "created": "创建时间",
    "expires": "过期时间",
    "collecting_bounded_metadata": "正在采集有界元数据…",
    "cancel_collection": "取消采集",
    "partial_bundle_one_or_more_sources_were": "部分完成：一个或多个来源已省略，使用前请检查清单。",
    "bundle_manifest": "诊断包清单",
    "source": "来源",
    "file": "文件",
    "bytes": "字节",
    "result": "结果",
    "included": "已包含",
    "prepare_download": "准备下载",
    "save_diagnostic_zip": "保存诊断 ZIP",
    "bytes_2": "字节",
    "server_completion_does_not_prove_the_browser": "服务端写出完成不证明浏览器已保存文件。",
    "no_archive_is_available_for_this_terminal": "该终态没有可下载归档。",
  }),
});

export function diagnosticsLabels(language) {
  return catalogs[language] ?? catalogs.en;
}
