const states=new Set(["collecting","ready","partial","failed","cancelled","expired"]),idPattern=/^[0-9a-f]{32}$/;
const text=(value,max=512)=>typeof value==="string"&&value.length>0&&value.length<=max;
export function diagnosticJob(value){
  if(!value||!idPattern.test(value.id)||value.profile!=="metadata-v1"||!states.has(value.state)||!text(value.createdAt)||!text(value.expiresAt)||Number.isNaN(Date.parse(value.createdAt))||Number.isNaN(Date.parse(value.expiresAt)))throw Error("invalid diagnostic job");
  if(value.finishedAt!==undefined&&(value.state==="collecting"||!text(value.finishedAt)||Number.isNaN(Date.parse(value.finishedAt))))throw Error("invalid diagnostic completion");
  let manifest=null;if(value.manifest!==undefined){if(!value.manifest||value.manifest.schema!=="rjs.diagnostics-manifest.v1"||!text(value.manifest.generatedAt)||!Array.isArray(value.manifest.entries)||value.manifest.entries.length>5)throw Error("invalid diagnostic manifest");manifest={schema:value.manifest.schema,generatedAt:value.manifest.generatedAt,entries:value.manifest.entries.map(entry=>{if(!entry||!text(entry.source)||!text(entry.collectedAt)||entry.file!==undefined&&!text(entry.file)||entry.size!==undefined&&(!Number.isSafeInteger(entry.size)||entry.size<0||entry.size>4<<20)||entry.sha256!==undefined&&!/^[0-9a-f]{64}$/.test(entry.sha256)||entry.error!==undefined&&!text(entry.error))throw Error("invalid diagnostic entry");return {...entry};})};}
  return {id:value.id,profile:value.profile,state:value.state,createdAt:value.createdAt,expiresAt:value.expiresAt,finishedAt:value.finishedAt,errorCode:value.errorCode,manifest};
}
export function createDiagnostics(api,{createURL=URL.createObjectURL,revokeURL=URL.revokeObjectURL}={}){
  let state={phase:"idle",job:null,error:null,download:null},controller=null,url=null,generation=0;const listeners=new Set(),emit=next=>{state=next;for(const fn of listeners)fn();};
  const clearDownload=()=>{if(url){revokeURL(url);url=null;}if(state.download)state={...state,download:null};};
  async function create(){if(state.phase==="creating"||state.job?.state==="collecting")return;clearDownload();controller?.abort();controller=new AbortController();const run=++generation;emit({phase:"creating",job:null,error:null,download:null});try{const result=await api.request("/api/v1/diagnostics/jobs",{method:"POST",body:{schema:"rjs.diagnostics-request.v1",profile:"metadata-v1"},signal:controller.signal});if(run===generation)emit({phase:"tracking",job:diagnosticJob(result.body),error:null,download:null});}catch(error){if(run===generation)emit({phase:"error",job:null,error:{status:error.status,code:error.code,kind:error.kind},download:null});}}
  async function refresh(){const current=state.job,run=generation;if(!current)return;try{const result=await api.request(`/api/v1/diagnostics/jobs/${current.id}`,{signal:controller?.signal});if(run!==generation||state.job?.id!==current.id)return;emit({...state,phase:"tracking",job:diagnosticJob(result.body),error:null});}catch(error){if(run===generation&&state.job?.id===current.id)emit({...state,phase:"error",error:{status:error.status,code:error.code,kind:error.kind}});}}
  async function cancel(){const current=state.job,run=generation;if(!current||current.state!=="collecting")return;try{const result=await api.request(`/api/v1/diagnostics/jobs/${current.id}`,{method:"DELETE",signal:controller?.signal});if(run===generation&&state.job?.id===current.id)emit({...state,phase:"tracking",job:diagnosticJob(result.body),error:null});}catch(error){if(run===generation&&state.job?.id===current.id)emit({...state,phase:"error",error:{status:error.status,code:error.code,kind:error.kind}});}}
  async function download(){const current=state.job,run=generation;if(!current||!["ready","partial"].includes(current.state))return;clearDownload();try{const result=await api.download(`/api/v1/diagnostics/jobs/${current.id}/download`,{signal:controller?.signal});if(run!==generation||state.job?.id!==current.id)return;url=createURL(result.blob);emit({...state,error:null,download:{url,size:result.size,filename:`rabbit-jetstream-diagnostics-${current.id}.zip`}});}catch(error){if(run===generation&&state.job?.id===current.id)emit({...state,phase:"error",error:{status:error.status,code:error.code,kind:error.kind}});}}
  return {snapshot:()=>state,subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);},create,refresh,cancel,download,clear(){generation++;controller?.abort();controller=null;clearDownload();emit({phase:"idle",job:null,error:null,download:null});}};
}
