// Formatting never writes a value back into a declaration or rounds an integer.
export function durationDisplay(value) {
  if(typeof value!=="bigint"&&!Number.isSafeInteger(value))return null;
  const nanos=BigInt(value);
  if(nanos<0n||nanos>9223372036854775807n)return null;
  if(nanos===0n)return "0s";
  for(const [unit,size] of [["h",3600000000000n],["m",60000000000n]])if(nanos%size===0n)return `${nanos/size}${unit}`;
  for(const [unit,size,digits] of [["s",1000000000n,9],["ms",1000000n,6],["µs",1000n,3]]){
    if(nanos<size)continue;
    const fraction=(nanos%size).toString().padStart(digits,"0").replace(/0+$/,"");
    return `${nanos/size}${fraction?`.${fraction}`:""}${unit}`;
  }
  return `${nanos}ns`;
}

// Reader completion times are generated by Date.toISOString, not audit event times.
// Reject any other representation instead of silently truncating extra precision.
export function readTimeDisplay(value,timeZone=Intl.DateTimeFormat().resolvedOptions().timeZone) {
  if(typeof value!=="string"||!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(value))return null;
  const date=new Date(value);
  if(!Number.isFinite(date.getTime())||date.toISOString()!==value)return null;
  try {
    const formatter=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23",timeZoneName:"longOffset"});
    const fields=Object.fromEntries(formatter.formatToParts(date).map(part=>[part.type,part.value]));
    const offset=fields.timeZoneName==="GMT"?"GMT+00:00":fields.timeZoneName;
    return `${fields.year}-${fields.month}-${fields.day} ${fields.hour}:${fields.minute}:${fields.second}.${value.slice(20,23)} (${formatter.resolvedOptions().timeZone}, ${offset})`;
  }catch{return null;}
}
