const catalogs = Object.freeze({
  en: Object.freeze({
    "dlq_diagnosis": "DLQ diagnosis",
    "invalid_dlq_plan_no_related_resource_reads": "Invalid DLQ plan; no related-resource reads were sent.",
    "no_dead_letter_target_is_configured_in": "No dead-letter target is configured in this declaration.",
    "not_observed": "Not observed",
    "reading": "Reading…",
    "observed_in_this_read": "Observed in this read",
    "not_found_in_this_read": "Not found in this read",
    "access_denied": "Access denied",
    "incompatible_response": "Incompatible response",
    "read_unavailable": "Read unavailable",
    "declared_target": "Declared target",
    "read_only_one_target_hop_declaration_target": "Read-only, one target hop. Declaration, target and controller reads are not an atomic snapshot. Existence does not prove ownership, readiness or successful transfer.",
    "refresh_dlq_evidence": "Refresh DLQ evidence",
    "dlq_target_declaration": "DLQ target declaration",
    "target_declaration": "Target declaration",
    "declaration_etag": "Declaration ETag",
    "unreported": "Unreported",
    "dlq_target_stream": "DLQ target Stream",
    "target_stream": "Target Stream",
    "dlq_controller_evidence": "DLQ controller evidence",
    "controller_process_all_queues": "Controller process — all Queues",
    "instance": "Instance",
    "enabled": "Enabled",
    "reports_leader": "Reports leader",
    "last_run": "Last run",
    "last_successful_run": "Last successful run",
    "error_reported": "Error reported",
    "reported_processed": "Reported processed",
    "reported_moved": "Reported moved",
    "reported_failed": "Reported failed",
    "reported_ignored": "Reported ignored",
    "counters_belong_to_this_controller_process_across": "Counters belong to this controller process across all Queues, can reset, and are not a complete transfer ledger. Leader/enabled flags are not health proof. Per-Queue transfer history is unavailable; no success is inferred from zero failures.",
    "these_are_processing_attempts_not_unique_messages": "These are processing attempts, not unique messages. Redelivered advisories can be counted again; moved can include an already-absent source message. A completed run can contain failed transfer attempts. Last successful run does not prove every transfer succeeded.",
    "ignored_counts_advisory_attempts_with_invalid_json": "Ignored counts advisory attempts with invalid JSON or no matching declared source. It does not prove message loss or completed acknowledgment. Missing counters remain unreported, not zero.",
  }),
  zh: Object.freeze({
    "dlq_diagnosis": "DLQ 诊断",
    "invalid_dlq_plan_no_related_resource_reads": "DLQ Plan 无效，未发送关联资源读取。",
    "no_dead_letter_target_is_configured_in": "此声明未配置死信目标。",
    "not_observed": "未观测",
    "reading": "正在读取…",
    "observed_in_this_read": "本次读取已观测",
    "not_found_in_this_read": "本次读取不存在",
    "access_denied": "访问被拒绝",
    "incompatible_response": "响应不兼容",
    "read_unavailable": "读取不可用",
    "declared_target": "声明目标",
    "read_only_one_target_hop_declaration_target": "只读且仅检查一层目标。声明、目标及控制器读取不是原子快照；存在不证明所有权、就绪或转移成功。",
    "refresh_dlq_evidence": "刷新 DLQ 证据",
    "dlq_target_declaration": "DLQ 目标声明",
    "target_declaration": "目标声明",
    "declaration_etag": "声明 ETag",
    "unreported": "未报告",
    "dlq_target_stream": "DLQ 目标 Stream",
    "target_stream": "目标 Stream",
    "dlq_controller_evidence": "DLQ 控制器证据",
    "controller_process_all_queues": "控制器进程 — 所有 Queue",
    "instance": "实例",
    "enabled": "已启用",
    "reports_leader": "报告为 Leader",
    "last_run": "上次运行",
    "last_successful_run": "上次成功运行",
    "error_reported": "报告存在错误",
    "reported_processed": "报告已处理",
    "reported_moved": "报告已转移",
    "reported_failed": "报告失败",
    "reported_ignored": "报告已忽略",
    "counters_belong_to_this_controller_process_across": "计数属于此控制器进程的所有 Queue，可能重置，不是完整转移台账。Leader/启用标志不是健康证明。尚无逐 Queue 转移历史，不按失败数为零推断成功。",
    "these_are_processing_attempts_not_unique_messages": "这些是处理尝试计数，不是去重消息数。重新投递的事件可能重复计数；已转移计数可包含源消息已不存在的情况。已完成的运行中也可能存在失败的转移尝试。上次成功运行不证明每次转移均成功。",
    "ignored_counts_advisory_attempts_with_invalid_json": "已忽略计数包括事件 JSON 无效或无法匹配声明来源的处理尝试，不证明消息丢失或确认已完成。缺失计数保持未报告，不补零。",
  }),
});

export function dLQDiagnosticsLabels(language) {
  return catalogs[language] ?? catalogs.en;
}
