import {latestRead} from "./api.mjs";
import {validObservationTime} from "./observation-time.mjs";
export const historyWindows=Object.freeze(["15m","1h","24h"]);
export const historyMetrics=Object.freeze(["jetstream-memory-bytes","jetstream-storage-bytes","queue-messages","queue-bytes","nats-nodes","management-uptime-seconds"]);
const finite=value=>typeof value==="string"&&value.length<=128&&Number.isFinite(Number(value));
export function metricHistory(value,expected){
  if(value?.schema!=="rjs.metric-history.v1"||value.source!=="prometheus"||value.metric!==expected.metric||value.window!==expected.window||!historyMetrics.includes(value.metric)||!historyWindows.includes(value.window)||!validObservationTime(value.start)||!validObservationTime(value.end)||![15,60,300].includes(value.stepSeconds)||!Array.isArray(value.series)||value.series.length>100)throw Error("invalid history");
  const start=Date.parse(value.start),end=Date.parse(value.end),steps={"15m":15,"1h":60,"24h":300};if(start>=end||value.stepSeconds!==steps[value.window])throw Error("invalid history range");const identities=new Set();
  const series=value.series.map(item=>{if(!item||Object.getPrototypeOf(item.labels)!==Object.prototype||!Array.isArray(item.samples)||item.samples.length>6000)throw Error("invalid history series");const labels={};for(const [key,label] of Object.entries(item.labels)){if(!["queue","status","instance"].includes(key)||typeof label!=="string"||label.length>256)throw Error("invalid history label");labels[key]=label;}const identity=JSON.stringify(labels);if(identities.has(identity))throw Error("duplicate history series");identities.add(identity);let previous=-Infinity;const samples=item.samples.map((sample,index)=>{if(!sample||!validObservationTime(sample.time)||!finite(sample.value)||sample.gapBefore!==undefined&&typeof sample.gapBefore!=="boolean"||sample.reset!==undefined&&typeof sample.reset!=="boolean"||index===0&&(sample.gapBefore||sample.reset)||sample.reset&&value.metric!=="management-uptime-seconds")throw Error("invalid history sample");const time=Date.parse(sample.time);if(time<start||time>end||time<=previous)throw Error("invalid history sample order");previous=time;return{time:sample.time,value:sample.value,gapBefore:sample.gapBefore===true,reset:sample.reset===true};});return{labels,samples};});
  return{schema:value.schema,source:value.source,metric:value.metric,window:value.window,start:value.start,end:value.end,stepSeconds:value.stepSeconds,series};
}
export function createMetricHistory(api,{metric="jetstream-storage-bytes",window="15m",queue=""}={}){
  if(queue&&!/^[A-Za-z0-9_-]+$/.test(queue))throw TypeError("invalid Queue identity");
  let selection={metric,window},state={phase:"idle",value:null,error:null},view={...state,selection:{...selection}};const listeners=new Set(),reader=latestRead(api),emit=next=>{state=next;view={...state,selection:{...selection}};for(const fn of listeners)fn();};
  const path=()=>{const params=new URLSearchParams(selection);if(queue)params.set("queue",queue);return `/api/v1/history?${params}`;};
  async function load(){reader.cancel();emit({phase:"loading",value:null,error:null});try{const result=await reader.run(path());if(result.stale)return;emit({phase:"ready",value:metricHistory(result.result.body,selection),error:null});}catch(error){emit({phase:"error",value:null,error:error.code==="history_api_disabled"?"disabled":error.status===401||error.status===403?"denied":"unavailable"});}}
  return{snapshot:()=>view,subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);},select(next){if(!historyMetrics.includes(next.metric)||!historyWindows.includes(next.window))throw TypeError("invalid history selection");selection={...next};void load();},load,clear(){reader.cancel();emit({phase:"idle",value:null,error:null});}};
}
