import React,{useEffect,useMemo,useSyncExternalStore} from "react";
import {createMetricHistory,historyWindows} from "./metric-history.mjs";

function segments(series,start,end,min,max){const width=760,height=220,pad=18,range=max-min||1,x=time=>pad+(Date.parse(time)-start)/(end-start)*(width-pad*2),y=value=>height-pad-(Number(value)-min)/range*(height-pad*2);const result=[];let current=[];for(const sample of series.samples){if((sample.gapBefore||sample.reset)&&current.length){result.push(current);current=[];}current.push(`${x(sample.time).toFixed(2)},${y(sample.value).toFixed(2)}`);}if(current.length)result.push(current);return{width,height,result};}
export function MetricHistory({api,language,queue="",metrics}){
  const zh=language==="zh",options=metrics??[{id:"jetstream-storage-bytes",en:"JetStream storage bytes",zh:"JetStream 存储字节"},{id:"jetstream-memory-bytes",en:"JetStream memory bytes",zh:"JetStream 内存字节"},{id:"management-uptime-seconds",en:"Management uptime seconds",zh:"管理服务运行秒数"}],model=useMemo(()=>createMetricHistory(api,{metric:options[0].id,queue}),[api,queue]),state=useSyncExternalStore(model.subscribe,model.snapshot),value=state.value;
  useEffect(()=>{void model.load();return()=>model.clear();},[model]);
  const all=value?.series.flatMap(item=>item.samples.map(sample=>Number(sample.value)))??[];let min=Infinity,max=-Infinity;for(const number of all){if(number<min)min=number;if(number>max)max=number;}if(!all.length)min=max=0;
  return <section className="metric-history" aria-label={zh?"历史指标":"Metric history"}><h3>{zh?"历史指标":"Metric history"}</h3><p>{zh?"来源为服务端配置的 Prometheus。缺口不会用连线填补；运行时间下降表示进程重置。空结果不是零。":"Source: server-configured Prometheus. Gaps are not connected; decreasing uptime marks a process reset. No samples does not mean zero."}</p>
    <form onSubmit={event=>{event.preventDefault();void model.load();}}><label>{zh?"指标":"Metric"}<select value={state.selection.metric} onChange={event=>model.select({metric:event.target.value,window:state.selection.window})}>{options.map(option=><option key={option.id} value={option.id}>{zh?option.zh:option.en}</option>)}</select></label><label>{zh?"时间范围":"Time window"}<select value={state.selection.window} onChange={event=>model.select({metric:state.selection.metric,window:event.target.value})}>{historyWindows.map(window=><option key={window}>{window}</option>)}</select></label><button disabled={state.phase==="loading"}>{zh?"刷新历史":"Refresh history"}</button></form>
    {state.phase==="loading"&&<p role="status">{zh?"正在查询历史数据…":"Querying history…"}</p>}{state.error&&<p role="alert">{state.error==="disabled"?(zh?"服务端未配置历史后端。":"History backend is not configured."):state.error==="denied"?(zh?"历史读取被拒绝。":"History read was denied."):(zh?"历史后端不可用或响应不兼容。":"History backend is unavailable or incompatible.")}</p>}
    {value&&<>{all.length===0?<p>{zh?"该范围没有样本；状态未知。":"No samples in this window; state is unknown."}</p>:value.series.map((series,index)=>{if(!series.samples.length)return null;const graph=segments(series,Date.parse(value.start),Date.parse(value.end),min,max);return <figure key={index}><svg viewBox={`0 0 ${graph.width} ${graph.height}`} role="img" aria-label={`${options.find(option=>option.id===value.metric)?.[zh?"zh":"en"]??value.metric}: ${series.samples.length} ${zh?"个样本":"samples"}`} preserveAspectRatio="none">{graph.result.map((points,i)=><polyline key={i} points={points.join(" ")} fill="none" stroke="currentColor" strokeWidth="3" vectorEffect="non-scaling-stroke"/>)}{series.samples.map(sample=>{const point=segments({samples:[sample]},Date.parse(value.start),Date.parse(value.end),min,max).result[0][0].split(",");return <circle key={sample.time} cx={point[0]} cy={point[1]} r="3" fill="currentColor"/>;})}</svg><figcaption>{Object.entries(series.labels).map(([key,label])=>`${key}=${label}`).join(", ")|| (zh?"默认序列":"Default series")}</figcaption></figure>})}{all.length>0&&<details><summary>{zh?"查看精确样本":"View exact samples"}</summary>{value.series.map((series,index)=><table key={index}><caption>{Object.entries(series.labels).map(([key,label])=>`${key}=${label}`).join(", ")||value.metric}</caption><thead><tr><th>{zh?"时间":"Time"}</th><th>{zh?"值":"Value"}</th><th>{zh?"证据":"Evidence"}</th></tr></thead><tbody>{series.samples.map(sample=><tr key={sample.time}><td><time dateTime={sample.time}>{sample.time}</time></td><td>{sample.value}</td><td>{[sample.gapBefore&&(zh?"采样缺口":"gap"),sample.reset&&(zh?"进程重置":"reset")].filter(Boolean).join(", ")||"—"}</td></tr>)}</tbody></table>)}</details>}</>}
  </section>;
}
