const catalogs = Object.freeze({
  en: Object.freeze({
    "access_and_settings": "Access and settings",
    "verified_session": "Verified session",
    "actor": "Actor",
    "role": "Role",
    "verified_expiry": "Verified expiry",
    "unknown_not_proof_of_an_unlimited_credential": "Unknown; not proof of an unlimited credential lifetime",
    "resource_read_policy": "Resource-read policy",
    "this_is_the_identity_verified_at_sign": "This is the identity verified at sign-in, not continuous proof of authorization. The server authorizes each request. An anonymous read policy does not allow anonymous writes or audit access.",
    "reported_permissions": "Reported permissions",
    "no_permissions_reported": "No permissions reported.",
    "permissions_do_not_prove_feature_availability_resource": "Permissions do not prove feature availability, resource ownership, cluster health or production qualification. Some permitted workflows are not yet implemented in this candidate.",
    "local_preferences_and_session": "Local preferences and session",
    "language_english_only_language_and_read_page": "Language: English. Only language and read-page refresh preferences are saved locally.",
    "switch_interface_language": "Switch interface language",
    "read_page_refresh_interval": "Read-page refresh interval",
    "manual_only": "Manual only",
    "seconds": "seconds",
    "applies_to_overview_queue_summaries_queue_stream": "Applies to Overview, Queue summaries, Queue/Stream lists and their Consumer collections, Stream configuration/state, node pages and standalone Consumer detail. Manual mode still reads on entry. Hidden tabs pause; failures back off up to 60 seconds. Drafts, previews and mutations are never refreshed by this preference. Other pages retain their existing refresh behavior.",
    "local_storage_is_unavailable_refresh_preference_applies": "Local storage is unavailable. Refresh preference applies to this page session only and was not saved.",
    "credentials_drafts_and_request_evidence_stay_in": "Credentials, drafts and request evidence stay in memory. Clearing this session discards them, preserves language and refresh preferences, and does not revoke credentials or cancel/roll back server operations.",
    "clear_this_session": "Clear this session",
    "not_yet_provided": "Not yet provided", "compatibility_link": "Build, SDK and server compatibility metadata",
    "production_qualification_evidence_is_not_supplied_here": "Production qualification evidence is not supplied here. Reachable node count is not used to infer qualification.",
  }),
  zh: Object.freeze({
    "access_and_settings": "访问与设置",
    "verified_session": "已验证会话",
    "actor": "身份",
    "role": "角色",
    "verified_expiry": "已验证到期时间",
    "unknown_not_proof_of_an_unlimited_credential": "未知，不代表凭据永久有效",
    "resource_read_policy": "资源读取策略",
    "this_is_the_identity_verified_at_sign": "这是登录时验证的身份，不是持续授权证明。服务端会校验每个请求。匿名读取策略不代表允许匿名写入或访问审计。",
    "reported_permissions": "服务端报告的权限",
    "no_permissions_reported": "未报告权限。",
    "permissions_do_not_prove_feature_availability_resource": "权限不证明功能可用、资源所有权、集群健康或生产资格。部分已授权流程尚未在候选界面实现。",
    "local_preferences_and_session": "本机偏好与会话",
    "language_english_only_language_and_read_page": "语言：简体中文。仅在本机保存语言和读取页面刷新偏好。",
    "switch_interface_language": "切换界面语言",
    "read_page_refresh_interval": "读取页面刷新间隔",
    "manual_only": "仅手动",
    "seconds": "秒",
    "applies_to_overview_queue_summaries_queue_stream": "作用于总览、Queue 摘要、Queue/Stream 列表及其 Consumer 集合、Stream 配置/状态、节点页面及独立 Consumer 详情。手动模式进入页面时仍读取一次。隐藏标签页暂停，失败退避最长 60 秒。此偏好不刷新草稿、预览或写入，其他页面保持原有刷新行为。",
    "local_storage_is_unavailable_refresh_preference_applies": "本机存储不可用，刷新偏好仅在当前页面会话生效，未保存。",
    "credentials_drafts_and_request_evidence_stay_in": "凭据、草稿和请求证据仅在内存。清除此会话会丢弃它们，保留语言和刷新偏好，但不会撤销凭据或取消/回滚服务端操作。",
    "clear_this_session": "清除此会话",
    "not_yet_provided": "尚未提供", "compatibility_link": "构建、SDK 与服务端兼容性元数据",
    "production_qualification_evidence_is_not_supplied_here": "此处尚不提供生产资格证据，不会通过可达节点数量推断资格。",
  }),
});

export function settingsLabels(language) {
  return catalogs[language] ?? catalogs.en;
}
