FROM --platform=$BUILDPLATFORM golang:1.25.13-alpine@sha256:1e0126852075c9c60731c8ba49088448b91f63e2aed97ca9d1a9791622a05946 AS build
ARG TARGETOS
ARG TARGETARCH
ARG NATSCLI_VERSION=v0.4.0
ARG VERSION=dev
ARG GOPROXY=https://goproxy.cn|https://proxy.golang.org|direct
ARG GOSUMDB=sum.golang.google.cn
WORKDIR /src
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY internal ./internal
COPY tools ./tools
RUN --mount=type=cache,target=/go/pkg/mod CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -trimpath -ldflags="-s -w -X main.version=${VERSION}" -o /out/rjsctl ./tools/rjsctl \
    && mkdir /src/natscli-build \
    && cd /src/natscli-build \
    && go mod init rabbit-jetstream.local/natscli-build \
    && go get github.com/nats-io/natscli/nats@${NATSCLI_VERSION} \
    && go get golang.org/x/crypto@v0.55.0 golang.org/x/net@v0.57.0 golang.org/x/text@v0.41.0 golang.org/x/term@v0.45.0 github.com/minio/highwayhash@v1.0.4 \
    && CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -trimpath -ldflags="-s -w" -o /out/nats github.com/nats-io/natscli/nats

FROM gcr.io/distroless/static-debian12:nonroot@sha256:f5b485ea962d9bd1186b2f6b3a061191539b905b82ec395de78cbfae51f20e35
COPY --from=build /out/rjsctl /usr/local/bin/rjsctl
COPY --from=build /out/nats /usr/local/bin/nats
ENV XDG_DATA_HOME=/tmp/nats-data
ENV XDG_CONFIG_HOME=/tmp/nats-config
ENTRYPOINT ["/usr/local/bin/rjsctl"]
