FROM golang:1.25.12-alpine AS build
ARG NATSCLI_VERSION=v0.4.0
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY internal ./internal
COPY tools ./tools
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/rjsctl ./tools/rjsctl \
    && mkdir /src/natscli-build \
    && cd /src/natscli-build \
    && go mod init rabbit-jetstream.local/natscli-build \
    && go get github.com/nats-io/natscli/nats@${NATSCLI_VERSION} \
    && go get golang.org/x/crypto@v0.52.0 golang.org/x/net@v0.55.0 golang.org/x/text@v0.39.0 golang.org/x/term@v0.43.0 github.com/minio/highwayhash@v1.0.4 \
    && CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/nats github.com/nats-io/natscli/nats

FROM alpine:3.23
RUN apk add --no-cache ca-certificates
COPY --from=build /out/rjsctl /usr/local/bin/rjsctl
COPY --from=build /out/nats /usr/local/bin/nats
ENV XDG_DATA_HOME=/tmp/nats-data
ENV XDG_CONFIG_HOME=/tmp/nats-config
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/rjsctl"]
