import test from "node:test";
import assert from "node:assert/strict";
import {createAlerts,decodeAlerts} from "../src/alerts.mjs";

const allNames=["RabbitJetStreamJetStreamUnavailable","RabbitJetStreamControllerStalled","RabbitJetStreamNATSNodeUnavailable","RabbitJetStreamDeadLetterFailures","RabbitJetStreamQueueBacklogHigh","RabbitJetStreamManagementHighErrorRate"],rule={name:"RabbitJetStreamQueueBacklogHigh",query:"rjs_queue_messages > 100000",duration:"900",severity:"warning",summary:"Backlog",description:"Threshold",state:"inactive"},body={schema:"rjs.operational-alerts.v1",source:"prometheus",observedAt:"2026-09-11T00:00:00Z",rules:[rule],missingRules:allNames.filter(name=>name!==rule.name)};

test("alert model reads only fixed endpoint and clears evidence on failure",async()=>{const calls=[];let fail=false;const api={async request(path){calls.push(path);if(fail)throw Object.assign(Error(),{status:503});return{body};}};const model=createAlerts(api);await model.load();assert.equal(model.snapshot().value.rules[0].state,"inactive");assert.deepEqual(calls,["/api/v1/alerts"]);fail=true;await model.load();assert.equal(model.snapshot().value,undefined);assert.equal(model.snapshot().failure,"unavailable");});
test("alert decoder requires observed recovery evidence and unique allowlisted rules",()=>{assert.throws(()=>decodeAlerts({...body,rules:[{...body.rules[0],state:"recovered"}]}));assert.throws(()=>decodeAlerts({...body,rules:[body.rules[0],body.rules[0]]}));assert.equal(decodeAlerts({...body,rules:[{...body.rules[0],state:"recovered",recoveredAt:"2026-09-11T00:01:00Z"}]}).rules[0].state,"recovered");});
test("alert console link is separately allowlisted and carries no credentials or query",()=>{assert.equal(decodeAlerts({...body,consoleUrl:"https://metrics.example/alerts"}).consoleUrl,"https://metrics.example/alerts");for(const consoleUrl of ["https://user:secret@metrics.example/alerts","https://metrics.example/alerts?q=x","https://metrics.example/graph","http://metrics.example/alerts"])assert.throws(()=>decodeAlerts({...body,consoleUrl}));});
